version: '3'
services:
  gluster-server1:
    image: ac3agrtp/centos6-glusterfs:3.12
    restart: always
    tty: true
    privileged: true
    volumes:
      - gluster-volume1
  gluster-server2:
    build: ./glusterfs
    restart: always
    tty: true
    privileged: true
    volumes:
      - gluster-volume2
    depends_on:
      - gluster-server1
  client:
    build: ./client
    restart: always
    tty: true
    privileged: true
    depends_on:
      - gluster-server1
      - gluster-server2
